name: "Publish to marketplace without build"
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Publish to VSCode Marketplace"
        uses: "lannonbr/vsce-action@510e61c5e9e6f33c0418ec5ff5fd36b1ced61e85" # v4.0.0
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
