name: "Publish to marketplace without build"
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: "ubuntu-latest"
    steps:
      - name: Fetch the repository code
        uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7

      - name: Setup Node
        uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace # v4.0.0
        with:
          node-version: 20
          cache: yarn

      - name: Lint
        run: |
          yarn lint

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
