name: "Publish to marketplace without build"
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: "ubuntu-latest"
    steps:
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VSCE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
