name: Update with latest themes and publish to marketplace
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # https://crontab.guru/every-week

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
      - name: Update schemes
        uses: tinted-theming/base16-builder-go@latest

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: |
          yarn install

      - name: Lint
        run: |
          yarn lint

      - name: Run update script
        run: |
          yarn update:packagejson:themes

      - name: Commit the changes, if any
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update with the latest colorschemes
          branch: ${{ github.head_ref }}
          commit_user_name: tinted-theming-bot
          commit_user_email: tintedtheming@proton.me
          commit_author: tinted-theming-bot <tintedtheming@proton.me>

      - name: Version bump if changes were comitted
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: |
          yarn version --minor

      - name: Publish to VSCode Marketplace
        uses: lannonbr/vsce-action@3.0.0
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
